import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import './globals.css';

export const metadata = {
  title: 'Mini Twitter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='bg-gradient-to-r from-violet-200 to-fuchsia-200'>
          <main >
            {children}
          </main>
      
      </body>
    </html>
  )
}
